language: go

go:
  - 1.x

env:
  - GO111MODULE=on APP_VERSION=v1.3.13

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install libgconf-2-4 # required by Cypress
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make deps

before_script:
  - make lint
  - make test

script:
  - make all ENV=prod
  - |
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_LOGIN" --password-stdin
    docker pull mongo:latest
    docker run -d --net=host mongo:latest
    docker pull oszura/sh-influxdb:v1.0.0
    docker run -d --net=host oszura/sh-influxdb:v1.0.0
    sleep 10
    docker pull oszura/sh-api-prod:v2.3.0
    docker run -d --net=host oszura/sh-api-prod:v2.3.2
    sleep 5
  - make image IMAGE_NAME=sh-panel ENV=prod V=$APP_VERSION
  - |
    # docker run -d --net=host -e SH_PANEL_CONFIGCAT_KEY=$SH_PANEL_CONFIGCAT_KEY oszura/sh-panel-prod:$APP_VERSION
    # sleep 5
    # npm run cypress:run

after_success:
  - |
    if [[ ($TRAVIS_PULL_REQUEST == "false") && ($TRAVIS_COMMIT_MESSAGE =~ ^Build.*) ]]
    then
      make image IMAGE_NAME=sh-panel ENV=dev V=$APP_VERSION
      docker push oszura/sh-panel-prod
      docker push oszura/sh-panel-dev
    fi

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE =~ ^Build.*
