language: go

go:
  - 1.x

env:
  - GO111MODULE=on APP_VERSION=v1.2.2

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install libgconf-2-4 # required by Cypress
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make deps

before_script:
  - make lint
  - make test
  - |
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_LOGIN" --password-stdin
    make image IMAGE_NAME=sh-panel ENV=test V=v1.2.2
    docker pull mongo:latest
    docker run -d --net=host mongo:latest
    docker pull oszura/sh-influxdb:v1.0.0
    docker run -d --net=host oszura/sh-influxdb:v1.0.0
    sleep 10
    docker pull oszura/sh-api-prod:v2.2.4
    docker run -d --net=host oszura/sh-api-prod:v2.2.4
    sleep 5
    docker pull oszura/sh-panel-prod:v1.2.2
    docker run -d --net=host oszura/sh-panel-prod:v1.2.2
    sleep 5
    docker pull oszura/sh-panel-dev:v1.2.2
    docker run -v --net=host -v $(pwd):/root/go/src/github.com/smart-evolution/shpanel oszura/sh-panel-test:v1.2.2

script:
  - make all ENV=prod

after_success:
  - |
    if [[ ($TRAVIS_PULL_REQUEST == "false") && ($TRAVIS_COMMIT_MESSAGE =~ ^Build.*) ]]
    then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_LOGIN" --password-stdin
      make image IMAGE_NAME=sh-panel ENV=prod V=$APP_VERSION
      docker push oszura/sh-panel-prod
      make image IMAGE_NAME=sh-panel ENV=dev V=$APP_VERSION
      docker push oszura/sh-panel-dev
    fi

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE =~ ^Build.*
