FROM debian:stretch

# Install generictools
RUN apt-get -y update && apt-get upgrade -y && apt-get install -y \
wget \
python \
vim \
git \
build-essential \
libcurl3 \
openssl

# Install mongodb
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - && \
echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list && \
apt-get -y update && \
apt-get install -y mongodb-org=4.2.0 mongodb-org-server=4.2.0 mongodb-org-shell=4.2.0 mongodb-org-mongos=4.2.0 mongodb-org-tools=4.2.0 && \
mkdir -p /data/db

RUN mkdir /root/scripts
COPY ./docker/entrypoint-shpanel-mongodb.sh /root/scripts

ENTRYPOINT /root/scripts/entrypoint-shpanel-mongodb.sh
