apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sh-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sh-panel
  template:
    metadata:
      labels:
        app: sh-panel
    spec:
      nodeName: debian
      containers:
        - image: oszura/sh-panel-prod:v1.2.3
          imagePullPolicy: IfNotPresent
          name: sh-panel
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "NOTIFIER_MSG=sh-panel $GOPATH/src/github.com/smart-evolution/smarthome-kubernetes/deployment-notifier.sh"]
        - image: mongo:latest
          imagePullPolicy: IfNotPresent
          name: sh-mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongo-db
      volumes:
        - name: mongo-db
          hostPath:
            path: /data/db-shpanel
            type: Directory
